# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whatever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=2)),
                ('universidade', models.CharField(max_length=20)),
            ],
        ),
    ]
